# Generated by Django 5.2.8 on 2025-12-01 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_recurringcardpurchase_recurringtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurring_transaction',
            field=models.ForeignKey(blank=True, help_text='Recorrente que gerou esta transação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='finance.recurringtransaction'),
        ),
    ]
